version: '3.8'

services:
  algranobot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
    restart: always
    volumes:
      - .:/app
    command: python main.py
